spring:
    datasource:
        password: bangtan
        url: jdbc:postgresql://localhost:5432/LetsOrder
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true